// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjgpyknugtxvsbeuzmcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqZ3B5a251Z3R4dnNiZXV6bWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDg3ODYsImV4cCI6MjA2OTcyNDc4Nn0.9tIDu7tV2SG8imkN8x8PnUfEglS_mW5YUefbJaD1WR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});